### ISSUE TITLE
Grant control to all members on the LAN without logging each in?

### ISSUE THREAD

**Issue by fpqc** [jaedb/spotmop#159]
Hi Jaedb, not sure if this is a spotmop issue or a mopidy-spotify one,  but I have set a uname and password in the mopidyctl config (running as a service in our office).  It seems weird that each user, who is basically doing no more than using spotmop as a remote control for the overhead speakers, has to use the office account to log in.

Is there any way to have spotmop automatically load the credentials from the mopidy system config?  Not sure if this is a bug report or feature request.

**Comment by jaedb** [comment]
The Mopidy server uses the same authentication credentials for all clients. In order to deliver the extra functionality to the client that is otherwise not available in the Libspotify SDK, Spotmop uses the Spotify HTTP API. Requests to this API require authentication and therefore is handled per-client.

Because the HTTP API's OAuth authentication opens full access to a person's Spotify account, it shouldn't be automatically shared to with other clients. This was covered extensively in #102 and was remedied by allowing clients to request access to another client's authentication tokens.

As a side-note, to you don't need to authenticate with Spotify to _use_ Spotmop. It is fully functional as a Mopidy web client without it, it just disables user-specific functions (like managing playlists, following artists, etc).

I hope this answers your question.

**Comment by fpqc** [comment]
Thanks!
