### ISSUE TITLE
search progress

### ISSUE THREAD

**Issue by mczerski** [jaedb/spotmop#161]
it would be nice if there was any search progress indication, just that the search is in progress.

**Comment by jaedb** [comment]
Because we use websockets (as per [mopidy.js](https://docs.mopidy.com/en/latest/api/js/)) there isn't an easy way to track the load progress of a request. This can be done for HTTP requests, which is when the loader is shown.

I'm exploring some other loader options in the next major release ([Iris](https://github.com/jaedb/Iris)) which may address this.
