### ISSUE TITLE
cannot connect more than one client browser

### ISSUE THREAD

**Issue by gaiterjones** [jaedb/spotmop#78]
Have installed mopidy and your web interface for use with spotify, works great from one client, but from others I just get mopidy server is offline in settings. i.e. i start mopidy (running on raspbian) login to the web client from my laptop and am asked to create a username and am connected. from 2nd or more clients, ipad, iphone etc the client settings say the server is offfline no matter what settings i enter. Spotify shows as online and I can browse spotify but cannot execute any mopidy commands, i.e. queue song etc. Am I missing a mopidy config for multiple connections or is this a mobile browser problem?

**Comment by jaedb** [comment]
@gaiterjones you will likely need to set the IP address (or domain name) of the server that is running the Mopidy server. You can find this on _Settings_ > _Mopidy Server_ section.

Out of the box it will work on your main client because (at a guess) that is the machine running Mopidy.

Let me know if this works.

**Comment by gaiterjones** [comment]
mopidy is running on a raspberry pi. the spotmop client seems to run ok on some devices and not at all on others, reporting that the server is offline when on another device it is working. strange will try another client and see if i see the same problems,
