### ISSUE TITLE
include spotify's suggestions into 'discover' section

### ISSUE THREAD

**Issue by sbctm** [jaedb/spotmop#83]
The spotify-webplayer shows a lot of useful suggestions for me under Browse -> discover, e.g. 'top recommendations' or 'because you listened to some band'. It would be awesome if spotmop could show these recommendations as well.

**Comment by jaedb** [comment]
@sbctm I agree. When you say _spotify-webplayer_ do you mean the [Spotify web application](https://play.spotify.com)? It's annoying because Spotify have kept the bulk of their recommendation engine from public access through their API.

That being said, now that Spotify is discontinuing Echonest, they have merged _some_ of the Echonest recommendation engine into the Spotify API.

This all means that we can build some basic suggestions. I've been working on this, and as of version `2.6.3` (95eb88e) this is up and running. Please see a screenshot below of this.

![discover](https://cloud.githubusercontent.com/assets/1711444/14652572/0061b766-06c9-11e6-990e-9ef9c0157867.jpg)

**Comment by sbctm** [comment]
@jaedb Yes, I meant the Spotify web application. The screenshot looks awesome, this is exactly what I was hoping for. Thanks a lot for your effort!

**Comment by sbctm** [comment]
@jaedb Sorry to bother you again with this. I have installed version 2.6.3 through pip and the Discover section does not look like your screenshot. I only have two sections there: 'some old favorites' and 'because you're listening to <what is currently playing>'.
The version bump to 2.6.3 is done in the commit you referred to, so I assume I should see the 'because you listened to' sections as well.

**Comment by jaedb** [comment]
@sbctm You may need to clear your browser cache completely as the templates have been changed as part of this release. Let me know if this fixes it.

**Comment by sbctm** [comment]
@jaedb Clearing the cache does not fix it for me. In fact I have first installed spotmop today, so 2.6.3 is the only version ever installed on my system.

**Comment by jaedb** [comment]
@sbctm Hmm, that is quite odd. I traced it back and it looked like the PyPi repository didn't include this functionality in the release. More than likely human error :-p

Pushed through release `2.6.4`, so give that a crack.

**Comment by sbctm** [comment]
@jaedb Now it's working as it should. Thanks a lot!
