### ISSUE TITLE
doubleclicking a search result adds the track to the beginning of the queue

### ISSUE THREAD

**Issue by choseh** [jaedb/spotmop#91]
doubleclicking a search result adds the track to the beginning of the queue and plays it - expected behavior might be: add as "play next" and leave current queue intact :)

cheers,
alex

**Comment by jaedb** [comment]
Given the intent of a double-click (to immediately execute the given target) I think the expected behavior would be to have this track play immediately. It is also more in line with the behavior exhibited in every modern OS.

The challenge in #68 was handling the existing playlist. Now, instead of copying the target track's (the one double-clicked) siblings and adding that to the queue, we just copy the target track. This is also accommodated when multiple tracks are targetted (when selected) and `<enter>` is pressed. 

I believe the net result is a more predictable UX. For _Play next_ we have both drag-and-drop functionality as well as the context menu.
